name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  specs:
    name: specs
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: alexellis/actions-post@master
     - name: uname
        run: uname -a
